### ISSUE TITLE
Deploy fails due to mongodb

### ISSUE THREAD

**Issue by humanely** [peec/laravel-aws#2]
Hi,

My laravel app runs on mongodb. I pasted my app in web folder, but the deploy fails with following error log. Please advice for how to install mongo ext before laravel?
Till now, I have added a file 001-pre.config
commands:
```
  # Allow to run SUDO comamnds for root.
  00sudo:
    command: 'echo Defaults:root \!requiretty >> /etc/sudoers'

commands:
  install_mongo_driver:
    command: pecl install mongo
    test: "php -r \"exit(extension_loaded('mongo') ? 1 : 0);\""
    command:  apachectl restart

files:
  "/etc/php.d/99mongo.ini" :
    mode: "000755"
    owner: root
    group: root
    content: |
      extension=mongo.so

```

Error log:

`Retrieving logs...
============= i-009599c415e602236 ==============

-------------------------------------
/var/log/eb-activity.log
-------------------------------------
  ++ export PHP_ZLIB_OUTPUT_COMPRESSION=Off
  ++ PHP_ZLIB_OUTPUT_COMPRESSION=Off
  ++ export PHP_DOCUMENT_ROOT=
  ++ PHP_DOCUMENT_ROOT=
  ++ export PHP_DATE_TIMEZONE=UTC
  ++ PHP_DATE_TIMEZONE=UTC
  ++ /opt/elasticbeanstalk/bin/get-config container -k app_staging_dir
  + EB_APP_STAGING_DIR=/var/app/ondeck
  + cd /var/app/ondeck
  + '[' -f composer.json ']'
  + export COMPOSER_HOME=/root
  + COMPOSER_HOME=/root
  + '[' -d vendor ']'
  ++ /opt/elasticbeanstalk/bin/get-config optionsettings -n aws:elasticbeanstalk:container:php:phpini -o composer_options
  + PHP_COMPOSER_OPTIONS=
  + echo 'Found composer.json file. Attempting to install vendors.'
  Found composer.json file. Attempting to install vendors.
  + composer.phar install --no-ansi --no-interaction
  Do not run Composer as root/super user! See https://getcomposer.org/root for details
  Loading composer repositories with package information
  Installing dependencies (including require-dev) from lock file
  Your requirements could not be resolved to an installable set of packages.
  
    Problem 1
      - Installation request for mongodb/mongodb 1.1.2 -> satisfiable by mongodb/mongodb[1.1.2].
      - mongodb/mongodb 1.1.2 requires ext-mongodb ^1.2.0 -> the requested PHP extension mongodb is missing from your system.
    Problem 2
      - mongodb/mongodb 1.1.2 requires ext-mongodb ^1.2.0 -> the requested PHP extension mongodb is missing from your system.
      - jenssegers/mongodb v3.2.2 requires mongodb/mongodb ^1.0.0 -> satisfiable by mongodb/mongodb[1.1.2].
      - Installation request for jenssegers/mongodb v3.2.2 -> satisfiable by jenssegers/mongodb[v3.2.2].
  
    To enable extensions, verify that they are enabled in your .ini files:
      - /etc/php.ini
`
